Unexpected error: (<class 'ConfigParser.NoSectionError'>, No section: 'Database', <traceback object at 0xeaab00>)
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "../py_scripts/ang_infra.py", line 66, in <module>
    populateLookups()
  File "../py_scripts/ang_infra.py", line 17, in populateLookups
    connection = Utility.KLPDB.getConnection()
  File "/home/megha/www/reports/ang_infra/py_scripts/Utility/KLPDB.py", line 9, in getConnection
    db = config.get('Database','dbname')
  File "/usr/lib/python2.6/ConfigParser.py", line 532, in get
    raise NoSectionError(section)
NoSectionError: No section: 'Database'
------------------------------------------------------------
